### ISSUE TITLE
Use log.debug instead of log.info

### ISSUE THREAD

**Issue by CyrilleB79** [cmillsap/XPoseImageCaptioner#2]
This add-on is logging many messages at "INFO" level. Most of them (if not all) are rather debug information and would deserve to be logged at "DEBUG" level instead of "INFO".

Could you please convert all log.info to log.debug? You may want to keep log.info for server starting/shutdown, but debug is also good; it's up to you.

**Comment by cmillsap** [comment]
changed all info messages to debug except for server startup and shutdown.  Fix will be in 0.8.8

**Comment by CyrilleB79** [comment]
> changed all info messages to debug except for server startup and shutdown. Fix will be in 0.8.8

Thanks!
